apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: hello-deploy
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
        - image:  nigelpoulton/pluralsight-docker-ci:latest
          name:  hello-pod
          ports:
            - containerPort: 8080