apiVersion: v1
kind: Pod
metadata:
  name: hello-pod
  labels:
    zone: prod
    version: v1
spec:
  containers:
    - image:  nigelpoulton/pluralsight-docker-ci:latest
      name:  hello-ctr
      ports:
        - containerPort: 8080