apiVersion: v1
kind: ReplicationController
metadata:
  name: hello-rc-blue
spec:
  replicas: 2
  selector:
    app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
        zone: prod
        version: v1
    spec:
      containers:
        - image:  nigelpoulton/pluralsight-docker-ci:latest
          name:  hello-pod
          ports:
            - containerPort: 8080